Update Buildkernel.yml

diff --git a/.github/workflows/Buildkernel.yml b/.github/workflows/Buildkernel.yml
--- a/.github/workflows/Buildkernel.yml
+++ b/.github/workflows/Buildkernel.yml
@@ -5,23 +5,23 @@ on:
       Android_Version:
         description: "Android Version"
         required: true
-        default: '14'
+        default: '15'
       Kernel_Version:
         description: "Kernel Version"
         required: true
-        default: '6.1'
+        default: '6.6'
       Security_Patch:
         description: "Security Patch or lts"
         required: true
-        default: '2025-06'
+        default: '2025-04'
       Kernel_Suffix:
         description: "Custom suffix to replace the dirty suffix (Just delete the dirty suffix,fill in [no])"
         required: false
-        default: 'ab13615898'
+        default: 'gd4aed7ed470e-ab13759939-4k'
       Kernel_Time:
         description: "Build Time"
         required: true
-        default: '2025-06-17 02:03:44 UTC'
+        default: 'Thu Jul 10 03:15:03 UTC 2025'
       Enable_KPM_Feature:
         description: "Enable KPM Feature"
         required: false
@@ -38,29 +38,29 @@ jobs:
       CCACHE_HARDLINK: "true"
 
     steps:
-      - name: Maximize Build Space
-        uses: AdityaGarg8/remove-unwanted-software@v5
-        with:
-          remove-dotnet: 'true'
-          remove-android: 'true'
-          remove-haskell: 'true'
-          remove-codeql: 'true'
-          remove-docker-images: 'true'
-          remove-large-packages: 'true'
-          remove-swapfile: 'true'
-          remove-cached-tools: 'false'
-          verbose: 'true'
+      #- name: Maximize Build Space
+        #uses: AdityaGarg8/remove-unwanted-software@v5
+        #with:
+          #remove-dotnet: 'true'
+          #remove-android: 'true'
+          #remove-haskell: 'true'
+          #remove-codeql: 'true'
+          #remove-docker-images: 'true'
+          #remove-large-packages: 'true'
+          #remove-swapfile: 'true'
+          #remove-cached-tools: 'false'
+          #verbose: 'true'
 
-      - name: Install toolkit
-        run: |
-         sudo apt update
-         sudo apt upgrade -y
-         sudo apt-get install -y curl git python3 zip
+      #- name: Install toolkit
+        #run: |
+         #sudo apt update
+         #sudo apt upgrade -y
+         #sudo apt-get install -y curl git python3 zip
           
       - name: Git for GKI
         run: |
-         git config --global user.name "user"
-         git config --global user.email "user@gmail.com"
+         git config --global user.name "user0"
+         git config --global user.email "user0@gmail.com"
 
       - name: Install repo
         run: |
@@ -75,12 +75,34 @@ jobs:
          repo init -u https://android.googlesource.com/kernel/manifest -b common-android${{ github.event.inputs.Android_Version }}-${{ github.event.inputs.Kernel_Version }}-${{ github.event.inputs.Security_Patch }} --depth=1
          repo sync
 
+      - name: Fix 6.6 Builds
+        run: |
+          cd Buildkernel/common
+          FORMATTED_BRANCH="android${{ github.event.inputs.Android_Version }}-${{ github.event.inputs.Kernel_Version }}"
+          # Fake Patch to fix failures
+          fake_patched=0
+          if [ "$FORMATTED_BRANCH" = "android15-6.6" ]; then
+            if ! grep -qxF $'\tunsigned int nr_subpages = __PAGE_SIZE / PAGE_SIZE;' ./fs/proc/task_mmu.c; then
+              echo "Can't find nr_subpages try to repair"
+              sed -i -e '/int ret = 0, copied = 0;/a \\tunsigned int nr_subpages \= __PAGE_SIZE \/ PAGE_SIZE;' -e '/int ret = 0, copied = 0;/a \\tpagemap_entry_t \*res = NULL;' ./fs/proc/task_mmu.c
+              fake_patched=1
+            fi
+          fi
+
+          if [ "$fake_patched" = 1 ]; then
+            if [ "$FORMATTED_BRANCH" = "android15-6.6" ]; then
+              if grep -qxF $'\tunsigned int nr_subpages = __PAGE_SIZE / PAGE_SIZE;' ./fs/proc/task_mmu.c; then
+                sed -i -e '/unsigned int nr_subpages \= __PAGE_SIZE \/ PAGE_SIZE;/d' -e '/pagemap_entry_t \*res = NULL;/d' ./fs/proc/task_mmu.c
+              fi
+            fi
+          fi
+
       - name: Setup SukiSU-Ultra
         run: |
          cd Buildkernel
          curl -LSs "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/main/kernel/setup.sh" | bash -s susfs-main
         
-      - name: Setup susfs and manual hooks
+      - name: Setup susfs & manual hooks
         run: |
          cd Buildkernel
          git clone https://gitlab.com/simonpunk/susfs4ksu.git -b gki-android${{ github.event.inputs.Android_Version }}-${{ github.event.inputs.Kernel_Version }}     
@@ -96,31 +118,27 @@ jobs:
       - name: Add susfs configuration to kernel
         run: |
          cd Buildkernel
-         CONFIGS=( 
-         "CONFIG_KSU=y"
-         "CONFIG_KSU_SUSFS_SUS_SU=n"
-         "CONFIG_KSU_MANUAL_HOOK=y"
-         "CONFIG_KSU_SUSFS=y"
-         "CONFIG_KSU_SUSFS_SUS_MAP=y"
-         "CONFIG_KSU_SUSFS_SUS_PATH=y"
-         "CONFIG_KSU_SUSFS_SUS_MOUNT=y"
-         "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_KSU_DEFAULT_MOUNT=y"
-         "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_BIND_MOUNT=y"
-         "CONFIG_KSU_SUSFS_SUS_KSTAT=y"
-         "CONFIG_KSU_SUSFS_SUS_OVERLAYFS=n"
-         "CONFIG_KSU_SUSFS_TRY_UMOUNT=y"
-         "CONFIG_KSU_SUSFS_AUTO_ADD_TRY_UMOUNT_FOR_BIND_MOUNT=y"
-         "CONFIG_KSU_SUSFS_SPOOF_UNAME=y"
-         "CONFIG_KSU_SUSFS_ENABLE_LOG=y"
-         "CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y"
-         "CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y"
-         "CONFIG_KSU_SUSFS_OPEN_REDIRECT=y"
-         "CONFIG_TMPFS_XATTR=y"
-         "CONFIG_TMPFS_POSIX_ACL=y"
-         )
-         for CONFIG in "${CONFIGS[@]}"; do
-         echo "$CONFIG" >> common/arch/arm64/configs/gki_defconfig
-         done
+         echo "CONFIG_KSU=y" >> ./common/arch/arm64/configs/gki_defconfig
+         echo "CONFIG_KSU_SUSFS_SUS_SU=n" >> ./common/arch/arm64/configs/gki_defconfig
+         echo "CONFIG_KSU_MANUAL_HOOK=y" >> ./common/arch/arm64/configs/gki_defconfig
+         echo "CONFIG_KSU_SUSFS=y" >> ./common/arch/arm64/configs/gki_defconfig
+         echo "CONFIG_KSU_SUSFS_SUS_MAP=y" >> ./common/arch/arm64/configs/gki_defconfig
+         echo "CONFIG_KSU_SUSFS_SUS_PATH=y" >> ./common/arch/arm64/configs/gki_defconfig
+         echo "CONFIG_KSU_SUSFS_SUS_MOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
+         echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_KSU_DEFAULT_MOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
+         echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_BIND_MOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
+         echo "CONFIG_KSU_SUSFS_SUS_KSTAT=y" >> ./common/arch/arm64/configs/gki_defconfig
+         echo "CONFIG_KSU_SUSFS_TRY_UMOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
+         echo "CONFIG_KSU_SUSFS_AUTO_ADD_TRY_UMOUNT_FOR_BIND_MOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
+         echo "CONFIG_KSU_SUSFS_SPOOF_UNAME=y" >> ./common/arch/arm64/configs/gki_defconfig
+         echo "CONFIG_KSU_SUSFS_ENABLE_LOG=y" >> ./common/arch/arm64/configs/gki_defconfig
+         echo "CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y" >> ./common/arch/arm64/configs/gki_defconfig
+         echo "CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y" >> ./common/arch/arm64/configs/gki_defconfig
+         echo "CONFIG_KSU_SUSFS_OPEN_REDIRECT=y" >> ./common/arch/arm64/configs/gki_defconfig
+         echo "CONFIG_TMPFS_XATTR=y" >> ./common/arch/arm64/configs/gki_defconfig
+         echo "CONFIG_TMPFS_POSIX_ACL=y" >> ./common/arch/arm64/configs/gki_defconfig
+         echo "CONFIG_CC_OPTIMIZE_FOR_PERFORMANCE=y" >> ./common/arch/arm64/configs/gki_defconfig
+         sed -i 's/check_defconfig//' ./common/build.config.gki
          echo -e "\e[33m[Done]\e[0m" Added susfs configuration to kernel
       
       - name: Add KPM configuration to kernel
@@ -133,20 +151,21 @@ jobs:
       - name: Set kernel suffix
         run: |
          cd Buildkernel
-         sudo sed -i 's/check_defconfig//' ./common/build.config.gki
          if [ "${{ github.event.inputs.Kernel_Suffix }}" = "no" ]; then
           sed -i '$i res=$(echo "$res" | sed '\''s/-dirty//g'\'')' common/scripts/setlocalversion
           echo -e "\e[33m[Done]\e[0m" Delete the dirty suffix
          else
-          sed -i '$i res=$(echo "$res" | sed '\''s/-dirty//g'\'')' common/scripts/setlocalversion
-          sed -i '$s|echo "\$res"|echo "\$res-${{ github.event.inputs.Kernel_Suffix }}"|' ./common/scripts/setlocalversion
+          sed -i "/stable_scmversion_cmd/s/-maybe-dirty//g" ./build/kernel/kleaf/impl/stamp.bzl
+          sed -i "\$s|echo \"\\\$res\"|echo \"-${{ github.event.inputs.kernel_suffix }}\"|" ./common/scripts/setlocalversion
+          sudo sed -i "s/-4k/-${{ github.event.inputs.Kernel_Suffix }}/g" ./common/arch/arm64/configs/gki_defconfig
           echo -e "\e[33m[Done]\e[0m" Setup custom suffix
          fi
 
       - name: Set kernel build time
         run: |
-         export SOURCE_DATE_EPOCH=$(date -d "${{ github.event.inputs.Kernel_Time }}" +%s)
-         echo "SOURCE_DATE_EPOCH=$SOURCE_DATE_EPOCH" >> $GITHUB_ENV
+         cd Buildkernel
+         perl -pi -e "s{UTS_VERSION=\"\\\$\(echo \\\$UTS_VERSION \\\$CONFIG_FLAGS \\\$TIMESTAMP \\| cut -b -\\\$UTS_LEN\)\"}{UTS_VERSION=\"#1 SMP PREEMPT ${{ github.event.inputs.Kernel_Time }}\"}" ./common/scripts/mkcompile_h
+         sed -i -e "s|\$(preempt-flag-y) \"\$(build-timestamp)\"|\$(preempt-flag-y) \"${{ github.event.inputs.Kernel_Time }}\"|" ./common/init/Makefile
          echo -e "\e[33m[Done]\e[0m" Setup kernel build time
 
       - name: Build kernel
@@ -154,8 +173,11 @@ jobs:
          cd Buildkernel
          sed -i '/^[[:space:]]*"protected_exports_list"[[:space:]]*:[[:space:]]*"android\/abi_gki_protected_exports_aarch64",$/d' ./common/BUILD.bazel
          rm -rf ./common/android/abi_gki_protected_exports_*
-         tools/bazel run --config=fast --config=stamp --lto=thin //common:kernel_aarch64_dist -- --destdir=dist
-
+         sed -i 's/BUILD_SYSTEM_DLKM=1/BUILD_SYSTEM_DLKM=0/' common/build.config.gki.aarch64
+         sed -i '/MODULES_ORDER=android\/gki_aarch64_modules/d' common/build.config.gki.aarch64
+         sed -i '/KMI_SYMBOL_LIST_STRICT_MODE/d' common/build.config.gki.aarch64
+         tools/bazel run --config=fast --lto=thin //common:kernel_aarch64_dist -- --destdir=dist
+         
       - name: KPM patch
         if: ${{inputs.Enable_KPM_Feature }}
         run: |
